# Generated by Django 3.2.8 on 2021-10-24 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
