# Generated by Django 3.2.8 on 2021-10-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0004_auto_20211017_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
