# Generated by Django 3.2.8 on 2021-10-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0007_rename_temp_id_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
