# Generated by Django 3.2.8 on 2021-10-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0010_auto_20211024_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.UUIDField(),
        ),
    ]
